const TAX_TYPE_ZERO = 'tax_zero';
const TAX_TYPE_INCLUDED = 'tax_included';

const PRODUCT_TYPE_NORMAL = 'normal';
const PRODUCT_TYPE_STORE = 'store';

const BID_MODE_BID = 'bid';
const BID_MODE_BUYOUT = 'buyout';

const TASK_STATUS_PENDING = 'pending';
const TASK_STATUS_PROCESSING = 'processing';
const TASK_STATUS_BIDDING = 'bidding';
const TASK_STATUS_SUCCESS = 'success';
const TASK_STATUS_FAILED = 'failed';
const TASK_STATUS_CANCELLED = 'cancelled';

const BID_STRATEGY_DIRECT = 'direct';
const BID_STRATEGY_MULTI_BID = 'multi_bid';
const BID_STRATEGY_SCOPE_ALL = 'all';
const BID_STRATEGY_SCOPE_DIRECT_ONLY = 'direct_only';

const ORDER_STATUS_PENDING_PAYMENT = 'pending_payment';
const ORDER_STATUS_WAITING_SHIPPING = 'waiting_shipping';
const ORDER_STATUS_PENDING_BUNDLE = 'pending_bundle';
const ORDER_STATUS_BUNDLE_COMPLETED = 'bundle_completed';
const ORDER_STATUS_PENDING_SETTLEMENT = 'pending_settlement';
const ORDER_STATUS_PENDING_SHIPMENT = 'pending_shipment';
const ORDER_STATUS_PENDING_RECEIPT = 'pending_receipt';
const ORDER_STATUS_CANCELLED = 'cancelled';
const ORDER_STATUS_COMPLETED = 'completed';

const ORDER_STATUS_LABELS = Object.freeze({
  [ORDER_STATUS_PENDING_PAYMENT]: '待支付',
  [ORDER_STATUS_WAITING_SHIPPING]: '等待发货',
  [ORDER_STATUS_PENDING_BUNDLE]: '待同捆',
  [ORDER_STATUS_BUNDLE_COMPLETED]: '同捆完成',
  [ORDER_STATUS_PENDING_SETTLEMENT]: '待结算',
  [ORDER_STATUS_PENDING_SHIPMENT]: '待发货',
  [ORDER_STATUS_PENDING_RECEIPT]: '待收货',
  [ORDER_STATUS_CANCELLED]: '已取消',
  [ORDER_STATUS_COMPLETED]: '完了'
});

const YAHOO_LOW_PRICE_THRESHOLD = 1000;
const YAHOO_LOW_PRICE_BID_LIMIT = 10000;
const YAHOO_LOW_PRICE_INITIAL_BID = 9000;
const YAHOO_LOW_PRICE_FOLLOWUP_THRESHOLD = 1200;
const DEFAULT_MULTI_BID_MIN_PRICE = 5000;

function isTerminalOrderStatus(status) {
  return status === ORDER_STATUS_COMPLETED || status === ORDER_STATUS_CANCELLED;
}

module.exports = {
  TAX_TYPE_ZERO,
  TAX_TYPE_INCLUDED,
  PRODUCT_TYPE_NORMAL,
  PRODUCT_TYPE_STORE,
  BID_MODE_BID,
  BID_MODE_BUYOUT,
  TASK_STATUS_PENDING,
  TASK_STATUS_PROCESSING,
  TASK_STATUS_BIDDING,
  TASK_STATUS_SUCCESS,
  TASK_STATUS_FAILED,
  TASK_STATUS_CANCELLED,
  BID_STRATEGY_DIRECT,
  BID_STRATEGY_MULTI_BID,
  BID_STRATEGY_SCOPE_ALL,
  BID_STRATEGY_SCOPE_DIRECT_ONLY,
  ORDER_STATUS_PENDING_PAYMENT,
  ORDER_STATUS_WAITING_SHIPPING,
  ORDER_STATUS_PENDING_BUNDLE,
  ORDER_STATUS_BUNDLE_COMPLETED,
  ORDER_STATUS_PENDING_SETTLEMENT,
  ORDER_STATUS_PENDING_SHIPMENT,
  ORDER_STATUS_PENDING_RECEIPT,
  ORDER_STATUS_CANCELLED,
  ORDER_STATUS_COMPLETED,
  ORDER_STATUS_LABELS,
  YAHOO_LOW_PRICE_THRESHOLD,
  YAHOO_LOW_PRICE_BID_LIMIT,
  YAHOO_LOW_PRICE_INITIAL_BID,
  YAHOO_LOW_PRICE_FOLLOWUP_THRESHOLD,
  DEFAULT_MULTI_BID_MIN_PRICE,
  isTerminalOrderStatus
};
