const assert=require('assert/strict');
if(!process.env.DATABASE_URL?.includes('gdaipai-regression-')) throw Error('isolated DB required');
const db=require('../models');
const accounts=require('../services/yahooAccounts');
const accountScope=require('../services/yahooAccountContext');
const plugin=require('./plugin');
const admin=require('./admin');
const express=require('express');
async function main(){
 db.raw.exec("INSERT INTO users(id,username,password_hash) VALUES(1,'review1','test'),(2,'review2','test')");
 const a=accounts.list(db,Date.now(),true)[0];
 const headers={'Content-Type':'application/json','X-Yahoo-Account':String(a.id),'X-Yahoo-Token':a.binding_token,'X-Yahoo-Instance':'review-instance-000001'};
 for(const [key,value] of [['payment_job_limit_min','2'],['payment_job_limit_max','2']]) db.raw.prepare('INSERT INTO config(key,value) VALUES(?,?) ON CONFLICT(key) DO UPDATE SET value=excluded.value').run(key,value);
 const app=express();app.use(express.json());app.use('/api/plugin',plugin);
 const server=await new Promise(resolve=>{const s=app.listen(0,'127.0.0.1',()=>resolve(s));});
 const base=`http://127.0.0.1:${server.address().port}`;
 const request=async(path,body)=>{const r=await fetch(base+'/api/plugin/'+path,{headers,method:body?'POST':'GET',...(body?{body:JSON.stringify(body)}:{})});const data=await r.json();assert.equal(r.status,200,JSON.stringify(data));return data;};
 const rows=[];
 try{
  for(const product of ['r123456781','r123456782']){
   db.raw.prepare('INSERT INTO products(product_id,product_title,product_type) VALUES(?,?,?)').run(product,product,'normal');
   const taskId=db.raw.prepare("INSERT INTO tasks(account_id,user_id,product_id,max_price,status) VALUES(?,1,?,2000,'success')").run(a.id,product).lastInsertRowid;
   db.raw.prepare('INSERT INTO yahoo_product_assignments(product_id,account_id,user_id,task_id) VALUES(?,?,1,?)').run(product,a.id,taskId);
   const orderId=db.raw.prepare("INSERT INTO orders(task_id,product_id,account_id,final_price,total_amount_cny,order_status) VALUES(?,?,?,1000,50,'pending_settlement')").run(taskId,product,a.id).lastInsertRowid;
   rows.push({taskId,orderId,product});
  }
  const first=(await request('payment/jobs')).jobs;assert.equal(first.length,2);
  await request('payment/status',{orderId:first[0].orderId,claim_token:first[0].claimToken,error:'review first payment failed before remaining jobs began'});
  assert.equal(db.raw.prepare("SELECT value FROM config WHERE key=?").get(`yahoo:${a.id}:payment_requested`).value,'0','payment error ends the requested payment run');
  assert.equal(db.raw.prepare('SELECT order_status FROM orders WHERE id=?').get(first[1].orderId).order_status,'pending_settlement','later order was not paid');
  const unused=first[1];
  await request('work/release',{kind:'payment',jobs:[{orderId:unused.orderId,claimToken:'wrong-token'}]});
  assert(db.raw.prepare('SELECT 1 FROM yahoo_work_claims WHERE kind=? AND object_id=?').get('payment',unused.orderId));
  await request('work/release',{kind:'payment',jobs:[{orderId:unused.orderId,claimToken:unused.claimToken}]});
  assert.notEqual((await request('idle-action/next')).action,'payment','returning unstarted claims does not resume payment automatically');
  await accountScope.run({accountId:a.id},()=>admin.clearPaymentAlertAndContinue(db));
  assert.equal(db.raw.prepare("SELECT value FROM config WHERE key=?").get(`yahoo:${a.id}:payment_requested`).value,'1','original manual continue starts a new payment run');
  const retry=(await request('payment/jobs')).jobs;
  assert.deepEqual(retry.map(j=>j.orderId),first.map(j=>j.orderId));
  await request('work/release',{kind:'payment',jobs:[{orderId:unused.orderId,claimToken:unused.claimToken}]});
  assert(db.raw.prepare('SELECT 1 FROM yahoo_work_claims WHERE kind=? AND object_id=?').get('payment',unused.orderId),'late release cannot clear a new claim');
  await request('payment/status',{orderId:retry[0].orderId,claim_token:retry[0].claimToken,status:'success'});
  await request('payment/status',{orderId:retry[1].orderId,claim_token:retry[1].claimToken,status:'success'});
  const after=(await request('payment/jobs')).jobs;
  assert.equal(after.length,0);
  assert.equal(db.raw.prepare('SELECT order_status FROM orders WHERE id=?').get(first[1].orderId).order_status,'pending_shipment');
  console.log('Unstarted payment recovery and stale release protection passed.');
  const b=accounts.save(db,{account_name:'B',email:'b@example.com',profile_dir:'B',yahoo_id:'review-b'}).id;
  const historical=db.raw.prepare("INSERT INTO tasks(account_id,user_id,product_id,max_price,status) VALUES(?,1,?,2000,'failed')").run(b,rows[0].product).lastInsertRowid;
  const reassigned=await admin.reassignOrderOwner(db,{orderId:rows[0].orderId,userId:2});
  assert.equal(reassigned.taskCount,2,'original owner change includes all same-product history of the old user');
  assert.equal(db.raw.prepare('SELECT user_id FROM tasks WHERE id=?').get(historical).user_id,2);
  assert.equal(db.raw.prepare('SELECT user_id FROM tasks WHERE id=?').get(rows[0].taskId).user_id,2);
  assert.equal(db.raw.prepare('SELECT user_id FROM yahoo_product_assignments WHERE product_id=?').get(rows[0].product).user_id,2);
  db.raw.prepare('UPDATE tasks SET force_orders_resync=1 WHERE id=?').run(rows[0].taskId);
  const synced=await request('orders/sync',{orders:[{productId:rows[0].product,price:1500}]});
  assert.equal(db.raw.prepare('SELECT final_price FROM orders WHERE id=?').get(rows[0].orderId).final_price,1500);
  assert.equal(db.raw.prepare('SELECT force_orders_resync FROM tasks WHERE id=?').get(rows[0].taskId).force_orders_resync,0);
  assert.equal(synced.forcedResync,1);
  db.raw.prepare('INSERT INTO yahoo_work_claims VALUES(?,?,?,?,?,?)').run(b,'scan',rows[1].orderId,'other-profile-000001','foreign-claim',Date.now());
  await request('work/release',{kind:'scan',jobs:[{orderId:rows[1].orderId,claimToken:'foreign-claim'}]});
  assert(db.raw.prepare('SELECT 1 FROM yahoo_work_claims WHERE account_id=?').get(b),'foreign account cannot release another account claim');
  db.raw.prepare('INSERT INTO yahoo_product_assignments(product_id,account_id,user_id) VALUES(?,?,1)').run(rows[0].product,b);
  await admin.reassignOrderOwner(db,{orderId:rows[0].orderId,userId:1});
  assert.equal(db.raw.prepare('SELECT user_id FROM tasks WHERE id=?').get(rows[0].taskId).user_id,1,'original admin reassignment is allowed even with a prior allocation');
  assert.equal(db.raw.prepare('SELECT user_id FROM tasks WHERE id=?').get(historical).user_id,1);
  assert.equal(db.raw.prepare('SELECT user_id FROM yahoo_product_assignments WHERE product_id=? AND account_id=?').get(rows[0].product,a.id).user_id,2);
  assert.equal(db.raw.prepare('SELECT user_id FROM yahoo_product_assignments WHERE product_id=? AND account_id=?').get(rows[0].product,b).user_id,1,'other account allocation must stay held');
  assert.equal(db.raw.prepare('SELECT account_id FROM orders WHERE id=?').get(rows[0].orderId).account_id,a.id,'order retains actual winning account');
  db.raw.prepare('UPDATE tasks SET force_orders_resync=1 WHERE id=?').run(rows[0].taskId);
  const resynced=await request('orders/sync',{orders:[{productId:rows[0].product,price:1800}]});
  assert.equal(resynced.forcedResync,1);
  assert.equal(db.raw.prepare('SELECT final_price FROM orders WHERE id=?').get(rows[0].orderId).final_price,1800);
  assert.equal(db.raw.prepare('SELECT user_id FROM tasks WHERE id=?').get(rows[0].taskId).user_id,1);
  assert.equal((await admin.reassignOrderOwner(db,{orderId:rows[0].orderId,userId:1})).taskCount,0);
  console.log('Original order owner history scope, existing allocations, won sync and idempotency passed.');
 }finally{server.closeAllConnections();await new Promise(resolve=>server.close(resolve));}
 db.raw.close();
}
main().catch(e=>{console.error(e);process.exitCode=1;});
