import assert from 'node:assert/strict';
import { favoritesKey, favoriteSnapshot, readFavorites, toggleFavorite, remainingFavoriteDays } from './productFavorites.js';

const data = new Map([['username', 'alice']]);
const storage = { getItem: key => data.get(key) ?? null, setItem: (key, value) => data.set(key, value) };
const key = favoritesKey(storage);
const now = Date.parse('2026-09-05T00:00:00Z');
const item = { auctionId: 'Q1242982152', title: 'Test', endTimeEpoch: (now + 1800000) / 1000, currentPrice: 1200 };
assert.equal(toggleFavorite(storage, key, item).added, true);
assert.equal(readFavorites(storage, key).length, 1);
assert.equal(readFavorites(storage, key)[0].auctionId, 'q1242982152');
assert.equal('currentPrice' in readFavorites(storage, key)[0], false);
assert.equal(remainingFavoriteDays(favoriteSnapshot(item).endTime, now), 1);
assert.equal(remainingFavoriteDays(new Date(now + 24.1 * 3600000).toISOString(), now), 2);
assert.equal(remainingFavoriteDays(new Date(now).toISOString(), now), 0);
assert.equal(remainingFavoriteDays(new Date(now - 1).toISOString(), now), 0);
assert.equal(remainingFavoriteDays('', now), null);
data.set('actingUsername', 'bob');
assert.equal(readFavorites(storage, favoritesKey(storage)).length, 0);
data.set('actingUsername', 'alice');
assert.equal(favoritesKey(storage), key);
assert.equal(toggleFavorite(storage, key, item).added, false);
assert.equal(readFavorites(storage, key).length, 0);
data.set(key, 'broken');
assert.deepEqual(readFavorites(storage, key), []);
assert.equal(toggleFavorite(storage, key, item).added, true);
assert.throws(() => toggleFavorite({ ...storage, setItem() { throw new Error('quota'); } }, key, item), /quota/);
assert.equal(readFavorites(storage, key).length, 1);
assert.equal(favoriteSnapshot({ auctionId: '../wrong' }), null);
console.log('productFavorites tests passed');
